routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//
//Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'namespace' => 'Admin',
    'as' => 'admin.',
    'prefix' => 'admin'
], function () {
    Route::get('/', 'LoginController@create')->name('auth.login')->middleware('guest');
    Route::post('login', 'LoginController@store')->name('auth.login.store')->middleware('guest');
    Route::get('forget-password', 'ForgetPasswordController@create')->name('forget-password');
    Route::post('forget-password', 'ForgetPasswordController@store')->name('forget-password.store');
    Route::group([
        'middleware' => ['adminAuth']
    ], function () {
        Route::get('logout', 'LoginController@destroy')->name('login.destroy');
        Route::any('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('profile', 'ProfileController@create')->name('profile');
        Route::post('profile/store', 'ProfileController@store')->name('profile.store');
        Route::get('change-password', 'ChangePasswordController@create')->name('change-password');
        Route::post('change-password/store', 'ChangePasswordController@store')->name('change-password.store');

        Route::get('customer/index', 'CustomerController@index')->name('customer.index');
        Route::get('customer/create', 'CustomerController@create')->name('customer.create');
        Route::post('customer/store', 'CustomerController@store')->name('customer.store');
        Route::get('customer/{user}/edit', 'CustomerController@edit')->name('customer.edit');
        Route::post('customer/{user}/update', 'CustomerController@update')->name('customer.update');
        Route::get('customer/{user}/delete', 'CustomerController@delete')->name('customer.delete');

        Route::get('vendor/index', 'VendorController@index')->name('vendor.index');
        Route::get('vendor/create', 'VendorController@create')->name('vendor.create');
        Route::post('vendor/store', 'VendorController@store')->name('vendor.store');
        Route::get('vendor/{user}/edit', 'VendorController@edit')->name('vendor.edit');
        Route::post('vendor/{user}/update', 'VendorController@update')->name('vendor.update');
        Route::get('vendor/{user}/delete', 'VendorController@delete')->name('vendor.delete');

    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//
//Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'namespace' => 'Website',
    'as' => 'website.',
], function () {
    Route::get('/redirect', 'FacebookController@redirect')->name('redirect');
    Route::get('/callback', 'FacebookController@callback')->name('callback');
    Route::get('/', 'LoginController@create')->name('login');
    Route::post('login', 'LoginController@store')->name('login.store');
    Route::get('customer/register', 'CustomerRegisterController@create')->name('customer.register');
    Route::post('customer/register/store', 'CustomerRegisterController@store')->name('customer.register.store');
    Route::get('vendor/register', 'VendorRegisterController@create')->name('vendor.register');
    Route::post('vendor/register/store', 'VendorRegisterController@store')->name('vendor.register.store');

    Route::group([
        'middleware' => ['auth']
    ], function () {
        Route::get('logout', 'LoginController@destroy')->name('login.destroy');
        Route::any('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('profile', 'ProfileController@create')->name('profile');
        Route::post('profile/store', 'ProfileController@store')->name('profile.store');
        Route::get('change-password', 'ChangePasswordController@create')->name('change-password');
        Route::post('change-password/store', 'ChangePasswordController@store')->name('change-password.store');
        Route::get('vendor-profile', 'VendorProfileController@create')->name('vendor-profile');
        Route::post('vendor-profile/store', 'VendorProfileController@store')->name('vendor-profile.store');
    });
});

resources/views/admin/change-password.blade.php
@extends('admin.layouts.master')

@section('title', 'Dashboard')

@section('content')
    <div class="container" style="margin-left: 200px;">
        <form action="{{ route('admin.change-password.store') }}"
              method="post">
            @csrf
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="form-group mb-4">
                                <label class="required">Password</label>
                                <input class="form-control form-control-sm" type="password" name="password"
                                       placeholder="Enter your Password" required>
                                @foreach($errors->get('password') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>

                            <div class="form-group mb-4">
                                <label class="required">Confirm Password</label>
                                <input class="form-control form-control-sm" type="password" name="password_confirmation"
                                       placeholder="Enter your Confirm Password" required>
                                @foreach($errors->get('password_confirmation') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>
                            <div class="btn text-center justify-content-center">
                                <button class="btn btn-success font-weight-bold" type="submit">
                                    Update
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.master')

@section('title', 'Dashboard')

@section('content')
    <div class="container">
        <h3> Hello !!</h3>
    </div>
@endsection

resources/views/admin/forget-password.blade.php
@extends('admin.layouts.master')

@section('title', 'Dashboard')

@section('content')
    <div class="container" style="margin-left: 200px;">
        <form action="{{ route('admin.forget-password.store') }}"
              method="post">
            @csrf
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="form-group mb-4">
                                <label class="required">Email</label>
                                <input class="form-control form-control-sm" type="email" name="email"
                                       placeholder="Enter your Password" required>
                                @foreach($errors->get('email') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>
{{--                            <div class="form-group mb-4">--}}
{{--                                <label class="required">Password</label>--}}
{{--                                <input class="form-control form-control-sm" type="password" name="password"--}}
{{--                                       placeholder="Enter your Password" required>--}}
{{--                                @foreach($errors->get('password') as $error)--}}
{{--                                    <div class="text-danger font-weight-bold">{{ $error }}</div>--}}
{{--                                @endforeach--}}
{{--                            </div>--}}

{{--                            <div class="form-group mb-4">--}}
{{--                                <label class="required">Confirm Password</label>--}}
{{--                                <input class="form-control form-control-sm" type="password" name="password_confirmation"--}}
{{--                                       placeholder="Enter your Confirm Password" required>--}}
{{--                                @foreach($errors->get('password_confirmation') as $error)--}}
{{--                                    <div class="text-danger font-weight-bold">{{ $error }}</div>--}}
{{--                                @endforeach--}}
{{--                            </div>--}}
                            <div class="btn text-center justify-content-center">
                                <button class="btn btn-success font-weight-bold" type="submit">
                                    Update
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/profile.blade.php
@extends('admin.layouts.master')

@section('title', 'Dashboard')

@section('content')
<div class="container" style="margin-left: 200px;">
    <form action="{{ route('admin.profile.store') }}"
          method="post">
        @csrf
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                            <div class="form-group mb-4">
                                <label class="required">First Name</label>
                                <input class="form-control form-control-sm" type="text" name="first_name"
                                  value="{{ old('first_name', $user->first_name) }}" placeholder="Enter your First Name" required>
                                @foreach($errors->get('first_name') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>

                        <div class="form-group mb-4">
                            <label class="required">Last Name</label>
                            <input class="form-control form-control-sm" type="text" name="last_name"
                                   value="{{ old('last_name', $user->last_name) }}" placeholder="Enter your Last Name" required>
                            @foreach($errors->get('last_name') as $error)
                                <div class="text-danger font-weight-bold">{{ $error }}</div>
                            @endforeach
                        </div>


                            <div class="form-group mb-4">
                                <label class="required">Email</label>
                                <input class="form-control form-control-sm" type="email" name="email"
                                       value="{{ old('email', $user->email) }}"  placeholder="Enter your email" required disabled>
                                @foreach($errors->get('email') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>
                            <div class="btn text-center justify-content-center">
                                <button class="btn btn-success font-weight-bold" type="submit">
                                    Update
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection