routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//
//Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'namespace' => 'Admin',
    'as' => 'admin.',
    'prefix' => 'admin'
], function () {
    Route::get('/', 'LoginController@create')->name('auth.login')->middleware('guest');
    Route::post('login', 'LoginController@store')->name('auth.login.store')->middleware('guest');
    Route::get('forget-password', 'ForgetPasswordController@create')->name('forget-password');
    Route::post('forget-password', 'ForgetPasswordController@store')->name('forget-password.store');
    Route::group([
        'middleware' => ['adminAuth']
    ], function () {
        Route::get('logout', 'LoginController@destroy')->name('login.destroy');
        Route::any('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('profile', 'ProfileController@create')->name('profile');
        Route::post('profile/store', 'ProfileController@store')->name('profile.store');
        Route::get('change-password', 'ChangePasswordController@create')->name('change-password');
        Route::post('change-password/store', 'ChangePasswordController@store')->name('change-password.store');

        Route::get('customer/index', 'CustomerController@index')->name('customer.index');
        Route::get('customer/create', 'CustomerController@create')->name('customer.create');
        Route::post('customer/store', 'CustomerController@store')->name('customer.store');
        Route::get('customer/{user}/edit', 'CustomerController@edit')->name('customer.edit');
        Route::post('customer/{user}/update', 'CustomerController@update')->name('customer.update');
        Route::get('customer/{user}/delete', 'CustomerController@delete')->name('customer.delete');

        Route::get('vendor/index', 'VendorController@index')->name('vendor.index');
        Route::get('vendor/create', 'VendorController@create')->name('vendor.create');
        Route::post('vendor/store', 'VendorController@store')->name('vendor.store');
        Route::get('vendor/{user}/edit', 'VendorController@edit')->name('vendor.edit');
        Route::post('vendor/{user}/update', 'VendorController@update')->name('vendor.update');
        Route::get('vendor/{user}/delete', 'VendorController@delete')->name('vendor.delete');

    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//
//Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'namespace' => 'Website',
    'as' => 'website.',
], function () {
    Route::get('/redirect', 'FacebookController@redirect')->name('redirect');
    Route::get('/callback', 'FacebookController@callback')->name('callback');
    Route::get('/', 'LoginController@create')->name('login');
    Route::post('login', 'LoginController@store')->name('login.store');
    Route::get('customer/register', 'CustomerRegisterController@create')->name('customer.register');
    Route::post('customer/register/store', 'CustomerRegisterController@store')->name('customer.register.store');
    Route::get('vendor/register', 'VendorRegisterController@create')->name('vendor.register');
    Route::post('vendor/register/store', 'VendorRegisterController@store')->name('vendor.register.store');

    Route::group([
        'middleware' => ['auth']
    ], function () {
        Route::get('logout', 'LoginController@destroy')->name('login.destroy');
        Route::any('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('profile', 'ProfileController@create')->name('profile');
        Route::post('profile/store', 'ProfileController@store')->name('profile.store');
        Route::get('change-password', 'ChangePasswordController@create')->name('change-password');
        Route::post('change-password/store', 'ChangePasswordController@store')->name('change-password.store');
        Route::get('vendor-profile', 'VendorProfileController@create')->name('vendor-profile');
        Route::post('vendor-profile/store', 'VendorProfileController@store')->name('vendor-profile.store');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    const REGISTERED_VIA_WEB = 1;
    const REGISTERED_VIA_ADMIN = 2;
    const REGISTERED_VIA_FACEBOOK = 3;
    const REGISTERED_VIA_GOOGLE = 4;

    const REGISTERED_VIA = [
        self::REGISTERED_VIA_WEB => 'Web',
        self::REGISTERED_VIA_ADMIN => 'Admin',
        self::REGISTERED_VIA_FACEBOOK => 'Facebook',
        self::REGISTERED_VIA_GOOGLE => 'Google',
    ];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function addNew($input)
    {
        $check = static::where('facebook_id',$input['facebook_id'])->first();


        if(is_null($check)){
            return static::create($input);
        }


        return $check;
    }
}

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Mail\SendUserMail;
use App\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Spatie\QueryBuilder\QueryBuilder;
use Throwable;
use Yajra\DataTables\Facades\DataTables;

class CustomerController extends Controller
{
    public function index(Request $request)
    {
//        if ($request->ajax()) {
//            $userQuery = QueryBuilder::for(User::class)
//                ->defaultSort('id');
//
//            if ($request->ajax()) {
//                return DataTables::of($userQuery)
//                    ->editColumn('created_at', function (User $user) {
//                        return $user->created_at->format('d:m:Y');
//                    })
//                    ->editColumn('name', function (User $user) {
//                        return $user->first_name.' '.$user->last_name;
//                    })
//                    ->addColumn('action', 'admin.customer.dataTable.action')
//                    ->rawColumns(['action'])
//                    ->addIndexColumn()
//                    ->toJson();
//            }
//        }

        $customers = User::whereHas('roles', function ($q) {
            $q->where('name', 'customer');
        })->get();

        return view('admin.customer.index', ['customers' => $customers]);
    }

    public function create()
    {
        return view('admin.customer.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'address' => 'required',
            'email' => 'required|email:rfc,dns',
        ]);

        $randomPwd = mt_rand(11111111, 99999999);
        $hashPwd = Hash::make($randomPwd);
//        try {
            DB::transaction(function () use ($request, $randomPwd, $hashPwd) {
                $user = User::create([
                    'first_name' => $request->get('first_name'),
                    'last_name' => $request->get('last_name'),
                    'email' => $request->get('email'),
                    'address' => $request->get('address'),
                    'password' => Hash::make($hashPwd),
                    'registered_via' => User::REGISTERED_VIA_ADMIN
                ]);
                $user->assignRole('customer');

                $details = [
                    'email' => $user->email,
                    'password' => $randomPwd
                ];

                Mail::to($user->email)->send(new SendUserMail($details));
            });

            return redirect()->route('admin.customer.index')->with(['success' => 'Customer created successfully!!']);


//        }
//        catch (Throwable $e) {
//            return redirect()->back()->with(['error' => 'Something went wrong. Please try again.'])->withInput();
//        }
    }

    public function edit(User $user)
    {
        return view('admin.customer.edit', ['customer' => $user]);
    }

    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'address' => 'required',
            'email' => 'required|email:rfc,dns',
        ]);

        $randomPwd = mt_rand(11111111, 99999999);
        $hashPwd = Hash::make($randomPwd);

        $user->update([
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'email' => $request->get('email'),
            'address' => $request->get('address'),
            'password' => Hash::make($hashPwd),
        ]);

        return redirect()->route('admin.customer.index')->with(['success' => 'Customer updated successfully!!']);
    }

    /**
     * @param User $user
     * @return RedirectResponse
     * @throws Exception
     */
    public function delete(User $user)
    {
        try {
            $user->delete();
        } catch (Exception $e) {
            return redirect()->back()->with(['error' => 'Something went wrong. Please try again.']);
        }

        return redirect()->route('admin.customer.index')->with(['success' => 'User deleted successfully.']);
    }
}

resources/views/user/customer/change-password.blade.php
@extends('user.layouts.master')

@section('title', 'Dashboard')

@section('content')
    <div class="container" style="margin-left: 200px;">
        <form action="{{ route('website.change-password.store') }}"
              method="post">
            @csrf
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="form-group mb-4">
                                <label class="required">Password</label>
                                <input class="form-control form-control-sm" type="password" name="password"
                                       placeholder="Enter your Password" required>
                                @foreach($errors->get('password') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>

                            <div class="form-group mb-4">
                                <label class="required">Confirm Password</label>
                                <input class="form-control form-control-sm" type="password" name="password_confirmation"
                                       placeholder="Enter your Confirm Password" required>
                                @foreach($errors->get('password_confirmation') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>
                            <div class="btn text-center justify-content-center">
                                <button class="btn btn-success font-weight-bold" type="submit">
                                    Update
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/user/customer/profile.blade.php
@extends('user.layouts.master')

@section('title', 'Dashboard')

@section('content')
    <div class="container" style="margin-left: 200px;">
        <form action="{{ route('website.profile.store') }}"
              method="post">
            @csrf
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="form-group mb-4">
                                <label class="required">First Name</label>
                                <input class="form-control form-control-sm" type="text" name="first_name"
                                       value="{{ old('first_name', $user->first_name) }}"
                                       placeholder="Enter your First Name" required>
                                @foreach($errors->get('first_name') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>

                            <div class="form-group mb-4">
                                <label class="required">Last Name</label>
                                <input class="form-control form-control-sm" type="text" name="last_name"
                                       value="{{ old('last_name', $user->last_name) }}"
                                       placeholder="Enter your Last Name" required>
                                @foreach($errors->get('last_name') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>


                            <div class="form-group mb-4">
                                <label class="required">Email</label>
                                <input class="form-control form-control-sm" type="email" name="email"
                                       value="{{ old('email', $user->email) }}" placeholder="Enter your email" required
                                       disabled>
                                @foreach($errors->get('email') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>

                            <div class="form-group mb-4">
                                <label class="required">Address</label>
                                <input class="form-control form-control-sm" type="text" name="address"
                                       value="{{ old('address', $user->address) }}"
                                       placeholder="Enter your Address" required>
                                @foreach($errors->get('address') as $error)
                                    <div class="text-danger font-weight-bold">{{ $error }}</div>
                                @endforeach
                            </div>

                            <div class="btn text-center justify-content-center">
                                <button class="btn btn-success font-weight-bold" type="submit">
                                    Update
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/user/customer/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title> Customer Registration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta content="admin" name="author">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body class="overflow-hidden">
<div class="container">
    <form action="{{ route('website.customer.register.store') }}"
          method="post">
        @csrf
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="bg-soft-primary">
                            <div class="row">
                                <div class="col-8">
                                    <div class="text-primary pl-3 mt-3">
                                        <p>Website Login</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body p-4">
                            <div class="row">
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label class="required">First Name</label>
                                        <input class="form-control form-control-sm" type="text" name="first_name"
                                              value="{{old('first_name')}}" placeholder="Enter your first name" required>
                                        @foreach($errors->get('first_name') as $error)
                                            <div class="text-danger font-weight-bold">{{ $error }}</div>
                                        @endforeach
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label class="required">Last Name</label>
                                        <input class="form-control form-control-sm" type="text" name="last_name"
                                               value="{{old('last_name')}}"  placeholder="Enter your last name" required>
                                        @foreach($errors->get('last_name') as $error)
                                            <div class="text-danger font-weight-bold">{{ $error }}</div>
                                        @endforeach
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label class="required">Email</label>
                                        <input class="form-control form-control-sm" type="email" name="email"
                                               value="{{old('email')}}" placeholder="Enter your email" required>
                                        @foreach($errors->get('email') as $error)
                                            <div class="text-danger font-weight-bold">{{ $error }}</div>
                                        @endforeach
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label class="required">Address</label>
                                        <input class="form-control form-control-sm" type="text" name="address"
                                               value="{{old('address')}}"  placeholder="Enter your address" required>
                                        @foreach($errors->get('address') as $error)
                                            <div class="text-danger font-weight-bold">{{ $error }}</div>
                                        @endforeach
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label class="required">Password</label>
                                        <input class="form-control form-control-sm" type="password" name="password"
                                               placeholder="Enter your password" required>
                                        @foreach($errors->get('password') as $error)
                                            <div class="text-danger font-weight-bold">{{ $error }}</div>
                                        @endforeach
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="form-group mb-4">
                                        <label class="required">Confirm Password</label>
                                        <input class="form-control form-control-sm" type="password" name="password_confirmation"
                                               placeholder="Enter your password_confirmation" required>
                                        @foreach($errors->get('password_confirmation') as $error)
                                            <div class="text-danger font-weight-bold">{{ $error }}</div>
                                        @endforeach
                                    </div>
                                </div>
                                <div class="col-8">
                                    <div class="btn text-center">
                                        <button class="btn btn-success font-weight-bold" type="submit">
                                            Register
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


</body>
</html>