routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//
//Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'namespace' => 'Admin',
    'as' => 'admin.',
    'prefix' => 'admin'
], function () {
    Route::get('/', 'LoginController@create')->name('auth.login')->middleware('guest');
    Route::post('login', 'LoginController@store')->name('auth.login.store')->middleware('guest');
    Route::get('forget-password', 'ForgetPasswordController@create')->name('forget-password');
    Route::post('forget-password', 'ForgetPasswordController@store')->name('forget-password.store');
    Route::group([
        'middleware' => ['adminAuth']
    ], function () {
        Route::get('logout', 'LoginController@destroy')->name('login.destroy');
        Route::any('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('profile', 'ProfileController@create')->name('profile');
        Route::post('profile/store', 'ProfileController@store')->name('profile.store');
        Route::get('change-password', 'ChangePasswordController@create')->name('change-password');
        Route::post('change-password/store', 'ChangePasswordController@store')->name('change-password.store');

        Route::get('customer/index', 'CustomerController@index')->name('customer.index');
        Route::get('customer/create', 'CustomerController@create')->name('customer.create');
        Route::post('customer/store', 'CustomerController@store')->name('customer.store');
        Route::get('customer/{user}/edit', 'CustomerController@edit')->name('customer.edit');
        Route::post('customer/{user}/update', 'CustomerController@update')->name('customer.update');
        Route::get('customer/{user}/delete', 'CustomerController@delete')->name('customer.delete');

        Route::get('vendor/index', 'VendorController@index')->name('vendor.index');
        Route::get('vendor/create', 'VendorController@create')->name('vendor.create');
        Route::post('vendor/store', 'VendorController@store')->name('vendor.store');
        Route::get('vendor/{user}/edit', 'VendorController@edit')->name('vendor.edit');
        Route::post('vendor/{user}/update', 'VendorController@update')->name('vendor.update');
        Route::get('vendor/{user}/delete', 'VendorController@delete')->name('vendor.delete');

    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//
//Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'namespace' => 'Website',
    'as' => 'website.',
], function () {
    Route::get('/redirect', 'FacebookController@redirect')->name('redirect');
    Route::get('/callback', 'FacebookController@callback')->name('callback');
    Route::get('/', 'LoginController@create')->name('login');
    Route::post('login', 'LoginController@store')->name('login.store');
    Route::get('customer/register', 'CustomerRegisterController@create')->name('customer.register');
    Route::post('customer/register/store', 'CustomerRegisterController@store')->name('customer.register.store');
    Route::get('vendor/register', 'VendorRegisterController@create')->name('vendor.register');
    Route::post('vendor/register/store', 'VendorRegisterController@store')->name('vendor.register.store');

    Route::group([
        'middleware' => ['auth']
    ], function () {
        Route::get('logout', 'LoginController@destroy')->name('login.destroy');
        Route::any('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('profile', 'ProfileController@create')->name('profile');
        Route::post('profile/store', 'ProfileController@store')->name('profile.store');
        Route::get('change-password', 'ChangePasswordController@create')->name('change-password');
        Route::post('change-password/store', 'ChangePasswordController@store')->name('change-password.store');
        Route::get('vendor-profile', 'VendorProfileController@create')->name('vendor-profile');
        Route::post('vendor-profile/store', 'VendorProfileController@store')->name('vendor-profile.store');
    });
});

resources/views/admin/layouts/header.blade.php
<nav class="navbar navbar-expand-sm bg-light" style="margin-left: 800px">
    <ul class="navbar-nav">
        <li class="nav-item">

        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Setting
                <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <a class="nav-link" href="{{ route('admin.profile') }}">Edit Profile</a>
                <a class="nav-link" href="{{ route('admin.change-password') }}">Change Password</a>
                <a class="nav-link" href="{{ route('admin.login.destroy') }}">Logout</a>
            </ul>
        </li>
    </ul>
</nav>

resources/views/admin/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <title>Pooja</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.css"/>
    <link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.devbridge-autocomplete/1.4.10/jquery.autocomplete.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/js/bootstrap-select.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.2.5/jquery.bootstrap-touchspin.min.js"></script>
</head>

<body>
<div class="container">
    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')
    <div id="main" class="row">
        @yield('content')
    </div>
</div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js"></script>
@if(Session::has('success'))
    <script>
        Swal.fire('Yay!!!', '{{ Session::get('success') }}', 'success')
    </script>
@endif

@if(Session::has('error'))
    <script>
        Swal.fire('Oops!!!', '{{ Session::get('error') }}', 'error')
    </script>
@endif

resources/views/admin/layouts/sidebar.blade.php
<nav class="navbar bg-light">
    <ul class="navbar-nav">
        <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.customer.index') }}"> Customers</a>
                <a class="nav-link" href="{{ route('admin.vendor.index') }}"> Vendors</a>
        </li>
    </ul>
</nav>