routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//
//Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'namespace' => 'Admin',
    'as' => 'admin.',
    'prefix' => 'admin'
], function () {
    Route::get('/', 'LoginController@create')->name('auth.login')->middleware('guest');
    Route::post('login', 'LoginController@store')->name('auth.login.store')->middleware('guest');
    Route::get('forget-password', 'ForgetPasswordController@create')->name('forget-password');
    Route::post('forget-password', 'ForgetPasswordController@store')->name('forget-password.store');
    Route::group([
        'middleware' => ['adminAuth']
    ], function () {
        Route::get('logout', 'LoginController@destroy')->name('login.destroy');
        Route::any('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('profile', 'ProfileController@create')->name('profile');
        Route::post('profile/store', 'ProfileController@store')->name('profile.store');
        Route::get('change-password', 'ChangePasswordController@create')->name('change-password');
        Route::post('change-password/store', 'ChangePasswordController@store')->name('change-password.store');

        Route::get('customer/index', 'CustomerController@index')->name('customer.index');
        Route::get('customer/create', 'CustomerController@create')->name('customer.create');
        Route::post('customer/store', 'CustomerController@store')->name('customer.store');
        Route::get('customer/{user}/edit', 'CustomerController@edit')->name('customer.edit');
        Route::post('customer/{user}/update', 'CustomerController@update')->name('customer.update');
        Route::get('customer/{user}/delete', 'CustomerController@delete')->name('customer.delete');

        Route::get('vendor/index', 'VendorController@index')->name('vendor.index');
        Route::get('vendor/create', 'VendorController@create')->name('vendor.create');
        Route::post('vendor/store', 'VendorController@store')->name('vendor.store');
        Route::get('vendor/{user}/edit', 'VendorController@edit')->name('vendor.edit');
        Route::post('vendor/{user}/update', 'VendorController@update')->name('vendor.update');
        Route::get('vendor/{user}/delete', 'VendorController@delete')->name('vendor.delete');

    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//
//Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'namespace' => 'Website',
    'as' => 'website.',
], function () {
    Route::get('/redirect', 'FacebookController@redirect')->name('redirect');
    Route::get('/callback', 'FacebookController@callback')->name('callback');
    Route::get('/', 'LoginController@create')->name('login');
    Route::post('login', 'LoginController@store')->name('login.store');
    Route::get('customer/register', 'CustomerRegisterController@create')->name('customer.register');
    Route::post('customer/register/store', 'CustomerRegisterController@store')->name('customer.register.store');
    Route::get('vendor/register', 'VendorRegisterController@create')->name('vendor.register');
    Route::post('vendor/register/store', 'VendorRegisterController@store')->name('vendor.register.store');

    Route::group([
        'middleware' => ['auth']
    ], function () {
        Route::get('logout', 'LoginController@destroy')->name('login.destroy');
        Route::any('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('profile', 'ProfileController@create')->name('profile');
        Route::post('profile/store', 'ProfileController@store')->name('profile.store');
        Route::get('change-password', 'ChangePasswordController@create')->name('change-password');
        Route::post('change-password/store', 'ChangePasswordController@store')->name('change-password.store');
        Route::get('vendor-profile', 'VendorProfileController@create')->name('vendor-profile');
        Route::post('vendor-profile/store', 'VendorProfileController@store')->name('vendor-profile.store');
    });
});

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Mail\SendUserMail;
use App\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Spatie\QueryBuilder\QueryBuilder;
use Throwable;
use Yajra\DataTables\Facades\DataTables;

class CustomerController extends Controller
{
    public function index(Request $request)
    {
//        if ($request->ajax()) {
//            $userQuery = QueryBuilder::for(User::class)
//                ->defaultSort('id');
//
//            if ($request->ajax()) {
//                return DataTables::of($userQuery)
//                    ->editColumn('created_at', function (User $user) {
//                        return $user->created_at->format('d:m:Y');
//                    })
//                    ->editColumn('name', function (User $user) {
//                        return $user->first_name.' '.$user->last_name;
//                    })
//                    ->addColumn('action', 'admin.customer.dataTable.action')
//                    ->rawColumns(['action'])
//                    ->addIndexColumn()
//                    ->toJson();
//            }
//        }

        $customers = User::whereHas('roles', function ($q) {
            $q->where('name', 'customer');
        })->get();

        return view('admin.customer.index', ['customers' => $customers]);
    }

    public function create()
    {
        return view('admin.customer.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'address' => 'required',
            'email' => 'required|email:rfc,dns',
        ]);

        $randomPwd = mt_rand(11111111, 99999999);
        $hashPwd = Hash::make($randomPwd);
//        try {
            DB::transaction(function () use ($request, $randomPwd, $hashPwd) {
                $user = User::create([
                    'first_name' => $request->get('first_name'),
                    'last_name' => $request->get('last_name'),
                    'email' => $request->get('email'),
                    'address' => $request->get('address'),
                    'password' => Hash::make($hashPwd),
                    'registered_via' => User::REGISTERED_VIA_ADMIN
                ]);
                $user->assignRole('customer');

                $details = [
                    'email' => $user->email,
                    'password' => $randomPwd
                ];

                Mail::to($user->email)->send(new SendUserMail($details));
            });

            return redirect()->route('admin.customer.index')->with(['success' => 'Customer created successfully!!']);


//        }
//        catch (Throwable $e) {
//            return redirect()->back()->with(['error' => 'Something went wrong. Please try again.'])->withInput();
//        }
    }

    public function edit(User $user)
    {
        return view('admin.customer.edit', ['customer' => $user]);
    }

    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'address' => 'required',
            'email' => 'required|email:rfc,dns',
        ]);

        $randomPwd = mt_rand(11111111, 99999999);
        $hashPwd = Hash::make($randomPwd);

        $user->update([
            'first_name' => $request->get('first_name'),
            'last_name' => $request->get('last_name'),
            'email' => $request->get('email'),
            'address' => $request->get('address'),
            'password' => Hash::make($hashPwd),
        ]);

        return redirect()->route('admin.customer.index')->with(['success' => 'Customer updated successfully!!']);
    }

    /**
     * @param User $user
     * @return RedirectResponse
     * @throws Exception
     */
    public function delete(User $user)
    {
        try {
            $user->delete();
        } catch (Exception $e) {
            return redirect()->back()->with(['error' => 'Something went wrong. Please try again.']);
        }

        return redirect()->route('admin.customer.index')->with(['success' => 'User deleted successfully.']);
    }
}

resources/views/admin/customer/create.blade.php
@extends('admin.layouts.master')

@section('title', 'Customers')

@section('content')
    <div class="container" style="margin-left: 200px;">
        <form action="{{ route('admin.customer.store') }}"
              method="post">
            @csrf
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="bg-soft-primary">
                                <div class="row">
                                    <div class="col-8">
                                        <div class="text-primary pl-3 mt-3">
                                            <p>Create Customer</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body p-4">
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group mb-4">
                                            <label class="required">First Name</label>
                                            <input class="form-control form-control-sm" type="text" name="first_name"
                                                   value="{{old('first_name')}}" placeholder="Enter your first name" required>
                                            @foreach($errors->get('first_name') as $error)
                                                <div class="text-danger font-weight-bold">{{ $error }}</div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group mb-4">
                                            <label class="required">Last Name</label>
                                            <input class="form-control form-control-sm" type="text" name="last_name"
                                                   value="{{old('last_name')}}"  placeholder="Enter your last name" required>
                                            @foreach($errors->get('last_name') as $error)
                                                <div class="text-danger font-weight-bold">{{ $error }}</div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group mb-4">
                                            <label class="required">Email</label>
                                            <input class="form-control form-control-sm" type="email" name="email"
                                                   value="{{old('email')}}" placeholder="Enter your email" required>
                                            @foreach($errors->get('email') as $error)
                                                <div class="text-danger font-weight-bold">{{ $error }}</div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group mb-4">
                                            <label class="required">Address</label>
                                            <input class="form-control form-control-sm" type="text" name="address"
                                                   value="{{old('address')}}"  placeholder="Enter your address" required>
                                            @foreach($errors->get('address') as $error)
                                                <div class="text-danger font-weight-bold">{{ $error }}</div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <div class="col-8">
                                        <div class="btn text-center">
                                            <button class="btn btn-success font-weight-bold" type="submit">
                                                Create
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/customer/edit.blade.php
@extends('admin.layouts.master')

@section('title', 'Customers')

@section('content')
    <div class="container" style="margin-left: 200px;">
        <form action="{{ route('admin.customer.update', ['user' => $customer]) }}"
              method="post">
            @csrf
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="bg-soft-primary">
                                <div class="row">
                                    <div class="col-8">
                                        <div class="text-primary pl-3 mt-3">
                                            <p>Edit Customer</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body p-4">
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group mb-4">
                                            <label class="required">First Name</label>
                                            <input class="form-control form-control-sm" type="text" name="first_name"
                                                   value="{{old('first_name', $customer->first_name)}}" placeholder="Enter your first name" required>
                                            @foreach($errors->get('first_name') as $error)
                                                <div class="text-danger font-weight-bold">{{ $error }}</div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group mb-4">
                                            <label class="required">Last Name</label>
                                            <input class="form-control form-control-sm" type="text" name="last_name"
                                                   value="{{old('last_name', $customer->last_name)}}"  placeholder="Enter your last name" required>
                                            @foreach($errors->get('last_name') as $error)
                                                <div class="text-danger font-weight-bold">{{ $error }}</div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group mb-4">
                                            <label class="required">Email</label>
                                            <input class="form-control form-control-sm" type="email" name="email"
                                                   value="{{old('email', $customer->email)}}" placeholder="Enter your email" required>
                                            @foreach($errors->get('email') as $error)
                                                <div class="text-danger font-weight-bold">{{ $error }}</div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group mb-4">
                                            <label class="required">Address</label>
                                            <input class="form-control form-control-sm" type="text" name="address"
                                                   value="{{old('address', $customer->address)}}"  placeholder="Enter your address" required>
                                            @foreach($errors->get('address') as $error)
                                                <div class="text-danger font-weight-bold">{{ $error }}</div>
                                            @endforeach
                                        </div>
                                    </div>
                                    <div class="col-8">
                                        <div class="btn text-center">
                                            <button class="btn btn-success font-weight-bold" type="submit">
                                                Update
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/customer/index.blade.php
@extends('admin.layouts.master')

@section('title', 'Customers')

@section('content')
    <div class="container">
        <div class="row" style="margin-left: 200px">
            <div class="col-lg-12 mx-auto">
                <div class="container">
                        <div class="btn-group" role="group" style="margin-left: 500px">
                            <a href="{{ route('admin.customer.create') }}"
                               class="btn btn-primary waves-effect waves-light font-weight-bold text-white">
                                <i class="mdi mdi-plus"></i> Create
                            </a>
                        </div>
                </div>
                <h4 class="header-title"> Customers</h4>
                <table class="table table-responsive">
                    <thead>
                    <tr>
                        <td>#</td>
                        <td>Created at</td>
                        <td>Name</td>
                        <td>Email</td>
                        <td>Address</td>
                        <td>Registered Via</td>
                        <td>Action</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($customers as $key => $customer)
                        <tr>
                            <td>{{ $key+1 }}</td>
                            <td>{{ $customer->created_at->format('d-m-Y') }}</td>
                            <td>{{ $customer->first_name }} {{ $customer->last_name }}</td>
                            <td>{{ $customer->email }}</td>
                            <td>{{ $customer->address }}</td>
                            <td>
                                @if( $customer->registered_via == 1) Web
                                @elseif($customer->registered_via == 2) Admin
                                @elseif($customer->registered_via == 3) Facebook
                                @else
                                    Google
                                @endif
                            </td>
                            <td> <a href="{{ route('admin.customer.delete',['user' => $customer]) }}"
                                    class="btn btn-primary waves-effect waves-light font-weight-bold text-white">
                                    <i class="mdi mdi-plus"></i> Delete
                                </a>
                                <a href="{{ route('admin.customer.edit',['user' => $customer]) }}"
                                   class="btn btn-primary waves-effect waves-light font-weight-bold text-white">
                                    <i class="mdi mdi-plus"></i> Edit
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection